/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-12 16:25:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FormCliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Gestión de Clientes</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #f0f8ff;\n");
      out.write("            color: #333;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            background-color: #fff;\n");
      out.write("            border: 2px solid #4CAF50;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            width: 80%;\n");
      out.write("            max-width: 800px;\n");
      out.write("        }\n");
      out.write("        h1 {\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("            padding: 20px;\n");
      out.write("            margin: -20px -20px 20px -20px;\n");
      out.write("            border-radius: 10px 10px 0 0;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .form-section {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        .form-section label, .form-section input {\n");
      out.write("            width: 48%;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .form-section button {\n");
      out.write("            width: 100%;\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("        .form-section button:hover {\n");
      out.write("            background-color: #45a049;\n");
      out.write("        }\n");
      out.write("        .back-button {\n");
      out.write("            width: 100%;\n");
      out.write("            background-color: #f44336;\n");
      out.write("            color: white;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("        .back-button:hover {\n");
      out.write("            background-color: #e53935;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>Gestión de Clientes</h1>\n");
      out.write("        <!-- Formulario para Registrar Cliente -->\n");
      out.write("        <form action=\"ClienteControl\" method=\"POST\" class=\"form-section\">\n");
      out.write("            <input type=\"hidden\" name=\"accion\" value=\"registrar\">\n");
      out.write("            <label>Nombre:</label>\n");
      out.write("            <input type=\"text\" name=\"nombre\" required>\n");
      out.write("            <label>Apellido:</label>\n");
      out.write("            <input type=\"text\" name=\"apellido\" required>\n");
      out.write("            <label>Dirección:</label>\n");
      out.write("            <input type=\"text\" name=\"direccion\" required>\n");
      out.write("            <label>Teléfono:</label>\n");
      out.write("            <input type=\"text\" name=\"telefono\" required>\n");
      out.write("            <button type=\"submit\">Registrar</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <!-- Formulario para Actualizar Cliente -->\n");
      out.write("        <form action=\"ClienteControl\" method=\"POST\" class=\"form-section\">\n");
      out.write("            <input type=\"hidden\" name=\"accion\" value=\"actualizar\">\n");
      out.write("            <label>ID Cliente (Actualizar):</label>\n");
      out.write("            <input type=\"number\" name=\"idCliente\" required>\n");
      out.write("            <label>Nombre:</label>\n");
      out.write("            <input type=\"text\" name=\"nombre\" required>\n");
      out.write("            <label>Apellido:</label>\n");
      out.write("            <input type=\"text\" name=\"apellido\" required>\n");
      out.write("            <label>Dirección:</label>\n");
      out.write("            <input type=\"text\" name=\"direccion\" required>\n");
      out.write("            <label>Teléfono:</label>\n");
      out.write("            <input type=\"text\" name=\"telefono\" required>\n");
      out.write("            <button type=\"submit\">Actualizar</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <!-- Formulario para Eliminar Cliente -->\n");
      out.write("        <form action=\"ClienteControl\" method=\"POST\" class=\"form-section\">\n");
      out.write("            <input type=\"hidden\" name=\"accion\" value=\"eliminar\">\n");
      out.write("            <label>ID Cliente (Eliminar):</label>\n");
      out.write("            <input type=\"number\" name=\"idCliente\" required>\n");
      out.write("            <button type=\"submit\">Eliminar</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <!-- Botón para ir a index.html -->\n");
      out.write("        <button class=\"back-button\" onclick=\"window.location.href='index.html'\">Volver a Inicio</button>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
